<a href="https://colab.research.google.com/github/AlejandroPSJ2/Data_Mining/blob/main/Clase5_regression_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# LIBRERIAS BASE

from google.colab import files
import io
import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [2]:
# FUNCIONES

def calculate_vif_(X):
    variables = list(range(X.shape[1]))
    vif = [variance_inflation_factor(X.iloc[:, variables].values, ix)
               for ix in range(X.iloc[:, variables].shape[1])]
    print(X.columns[variables])
    return vif

In [7]:
#LOCAL DATA LOADING & PREVIEW

uploaded = files.upload()                                       ##Seleccionar archivo
df = pd.read_csv(io.BytesIO(uploaded['d1_diabetes.csv']))       ##dentro de los corchetes colocar el nombre del archivo original 
df.head()

Saving d1_diabetes.csv to d1_diabetes (2).csv

,ID,N_pregnant,Plasma,Diastolic_pressure,Triceps_thickness,Serum_insulin,BMI,Diabetes_function,Age,Diabetes_future
0,1,6,148,72,35,0,33.6,0.627,50,1
1,2,1,85,66,29,0,26.6,0.351,31,0
2,3,8,183,64,0,0,23.3,0.672,32,1
3,4,1,89,66,23,94,28.1,0.167,21,0
4,5,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
#DATA LOADING & PREVIEW

url = 'https://raw.githubusercontent.com/AlejandroPSJ2/Data_Mining/main/Clase5_example1_car.csv'
df = pd.read_csv(url,sep=';')
df.head()

  Car_Name  N_years  Selling_Price  ...  Seller_Type  Transmission Owner
0     ritz        4           3.35  ...       Dealer        Manual     0
1      sx4        5           4.75  ...       Dealer        Manual     0
2     ciaz        1           7.25  ...       Dealer        Manual     0
3  wagon r        7           2.85  ...       Dealer        Manual     0
4    swift        4           4.60  ...       Dealer        Manual     0

[5 rows x 9 columns]

In [8]:
#DATA PREPARATION (VERY IMPORTANT TO DIFFERENTIATE "X" AND "DF")

X = df.drop(columns=['ID','Diabetes_future'])  # PRIMERO ELIMINAR VARIABLES QUE NO VAN A IR EN EL ALGORITMO
X = pd.get_dummies(X)  # ACA SE CREAN DUMMIES (EN CASO HAYA ALGUNA VARIABLE CATEGORICA, SI NO HAY NO CREARA NADA)
X.head()

,N_pregnant,Plasma,Diastolic_pressure,Triceps_thickness,Serum_insulin,BMI,Diabetes_function,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [ ]:
X = X.drop(columns=['Fuel_Type_CNG','Seller_Type_Individual','Transmission_Manual'])   # EN CASO ESTEMOS CREANDO DUMMIES PARA CATEGORICAS SIEMPRE ELIMINAR 1 DE LAS N OPCIONES QUE SE CREAN (SOLO QUEDARIAN N-1 FLAGS POR CADA CATEGORICA)
X.head()

   N_years  Selling_Price  ...  Seller_Type_Dealer  Transmission_Automatic
0        4           3.35  ...                   1                       0
1        5           4.75  ...                   1                       0
2        1           7.25  ...                   1                       0
3        7           2.85  ...                   1                       0
4        4           4.60  ...                   1                       0

[5 rows x 9 columns]

In [9]:
# ALGORITHM FIT

dep = 'Diabetes_function'  # ACA SOLO MODIFICAR LA VARIABLE DEPENDIENTE "dep", DEJAR TODO LO DEMAS IGUAL

mod = sm.OLS(X[dep], sm.add_constant(X.drop(columns=[dep])))    
res = mod.fit()
print(res.summary())
print('')
print('')
print('')
print('VIF RESULTS')
print('')
calculate_vif_(X.drop(columns=[dep]))

                            OLS Regression Results
==============================================================================
Dep. Variable:      Diabetes_function   R-squared:                       0.063
Model:                            OLS   Adj. R-squared:                  0.054
Method:                 Least Squares   F-statistic:                     7.284
Date:                Sat, 25 Feb 2023   Prob (F-statistic):           1.80e-08
Time:                        21:49:27   Log-Likelihood:                -215.94
No. Observations:                 768   AIC:                             447.9
Df Residuals:                     760   BIC:                             485.0
Df Model:                           7
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
const                  0.2075      0.068      3.034      0.002       0.073       0.342
N_pregnant            -0.0060      0.004     -1.459      0.145      -0.014       0.002
Plasma                 0.0008      0.000      1.996      0.046    1.36e-05       0.002
Diastolic_pressure    -0.0005      0.001     -0.796      0.426      -0.002       0.001
Triceps_thickness      0.0025      0.001      2.861      0.004       0.001       0.004
Serum_insulin          0.0003      0.000      2.239      0.025    3.32e-05       0.001
BMI                    0.0027      0.002      1.590      0.112      -0.001       0.006
Age                    0.0019      0.001      1.557      0.120      -0.001       0.004
==============================================================================
Omnibus:                      281.715   Durbin-Watson:                   2.024
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1024.228
Skew:                           1.735   Prob(JB):                    3.91e-223
Kurtosis:                       7.468   Cond. No.                     1.09e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.09e+03. This might indicate that there are
strong multicollinearity or other numerical problems.



VIF RESULTS

Index(['N_pregnant', 'Plasma', 'Diastolic_pressure', 'Triceps_thickness',
       'Serum_insulin', 'BMI', 'Age'],
      dtype='object')

/usr/local/lib/python3.8/dist-packages/statsmodels/tsa/tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

[3.263115822423506,
 16.454706050648813,
 14.618932287341325,
 3.9646632971128217,
 2.0548607668795995,
 18.155256472349848,
 13.395010984343982]